src/Entities/Property.cs
using System;

namespace RealEstate.Entities
{
	public class Property
	{
		public int Id { get; set; }
		public string Name { get; set; }
		public string Description { get; set; }
		public float Price { get; set; }
		public int NumberOfBathrooms { get; set; }
		public int NumberOfBedrooms { get; set; }
		public DateTimeOffset LastUpdatedUtc { get; set; }
	}
}

src/Entities/RealEstateObject.cs
using System;

namespace RealEstate.Entities
{
	public class RealEstateObject
	{
		public int Id { get; set; }
		public string Name { get; set; }
		public string Description { get; set; }
		public float Price { get; set; }
		public int NumberOfBathrooms { get; set; }
		public int NumberOfBedrooms { get; set; }
		public DateTimeOffset LastUpdatedUtc { get; set; }
	}
}

src/Models/BaseViewModel.cs
namespace RealEstate.Models
{
	public class BaseViewModel
	{
		public bool ShowMasterHeader { get; set; }
	}
}

src/Models/ErrorViewModel.cs
using System;

namespace RealEstate.Models
{
	public class ErrorViewModel : BaseViewModel
	{
		public string RequestId { get; set; }

		public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
	}
}

src/Models/HomeViewModel.cs
using RealEstate.Entities;
using System.Collections.Generic;

namespace RealEstate.Models
{
	public class HomeViewModel : BaseViewModel
	{
		public List<PropertyViewModel> FeaturedProperties { get; set; }
	}
}

src/Models/PropertyListViewModel.cs
using System.Collections.Generic;

namespace RealEstate.Models
{
	public class PropertyListViewModel : BaseViewModel
	{
		public List<PropertyViewModel> Properties { get; set; }
	}
}

src/Models/PropertyViewModel.cs
using RealEstate.Entities;

namespace RealEstate.Models
{
	public class PropertyViewModel: BaseViewModel
	{
		public Property Property { get; set; }
		public string ImageUrl { get; set; }
	}
}

src/Models/RealEstateObjectViewModel.cs
using RealEstate.Entities;

namespace RealEstate.Models
{
	public class RealEstateObjectViewModel : BaseViewModel
	{
		public RealEstateObject Object { get; set; }
		public string ImageUrl { get; set; }
	}
}

src/ViewModels/HomeViewModel.cs
using RealEstate.Entities;
using System.Collections.Generic;

namespace RealEstate.ViewModels
{
	public class HomeViewModel
	{
		public List<RealEstateObject> FeaturedObjects { get; set; }
	}
}

src/Controllers/HomeController.cs
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using RealEstate.Models;
using RealEstate.Services;

namespace RealEstate.Controllers
{
	[Route("")]
	public class HomeController : Controller
	{
		public HomeController(IDataRepository repo)
		{
			_repo = repo;
		}

		readonly IDataRepository _repo;

		[HttpGet]
		public async Task<IActionResult> Index()
		{
			var featuredProperties = await _repo.GetFeaturedProperties();

            var vm = new HomeViewModel
			{
				ShowMasterHeader = true,
				FeaturedProperties = featuredProperties.Select(r => r.ToViewModel()).ToList()
            };

			return View(vm);
		}

		[HttpGet("propertydetailsmodal/{propertyId}", Name = "PropertyDetailsRoute")]
		public async Task<ActionResult> PropertyDetailsPartial(int propertyId)
		{
			var propertyDetails = await _repo.GetPropertyDetails(propertyId);

			var vm = propertyDetails.ToViewModel();
			return PartialView("_PropertyDetailsModal", vm);
		}

		public IActionResult Privacy()
		{
			return View();
		}

		[ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
		public IActionResult Error()
		{
			return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
		}
	}
}

src/Controllers/PropertiesListController.cs
using Microsoft.AspNetCore.Mvc;
using RealEstate.Models;
using RealEstate.Services;
using System.Linq;
using System.Threading.Tasks;

namespace RealEstate.Controllers
{
	[Route("properties")]
    public class PropertiesListController : Controller
    {
		public PropertiesListController(IDataRepository repo)
		{
			_repo = repo;
		}

		readonly IDataRepository _repo;

		[HttpGet("")]
		public async Task<ActionResult> GetAllProperties()
        {
			var properties = await _repo.GetAllProperties();
			var vm = new PropertyListViewModel {
				Properties = properties.Select(r => r.ToViewModel()).ToList()
			};
            return View("List", vm);
        }
    }
}

src/Controllers/PropertyDetailsController.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using RealEstate.Models;
using RealEstate.Services;

namespace RealEstate.Controllers
{
	[Route("properties")]
	public class PropertyDetailsController : Controller
    {
        public PropertyDetailsController(IDataRepository repo)
		{
			_repo = repo;
		}

		readonly IDataRepository _repo;


		[Route("{propertyId}")]
        public async Task<IActionResult> Details(int propertyId)
        {
			var propertyDetails = await _repo.GetPropertyDetails(propertyId);

			var vm = new PropertyViewModel
			{
				Property = propertyDetails,
				ImageUrl = $"/assets/propertyimages/property-{propertyDetails.Id}.jpg"
			};

			return View(vm);
        }
    }
}

src/Views/Home/Index.cshtml
@model RealEstate.Models.HomeViewModel
@{
    ViewData["Title"] = "Home Page";
}

<!-- Portfolio Section Heading -->
<h2 class="page-section-heading text-center text-uppercase text-secondary mb-0">Featured properties</h2>

<!-- Icon Divider -->
<div class="divider-custom">
    <div class="divider-custom-line"></div>
    <div class="divider-custom-icon">
        <i class="fas fa-star"></i>
    </div>
    <div class="divider-custom-line"></div>
</div>

<!-- Portfolio Grid Items -->
<div class="row">

    @foreach (var featuredProperty in Model.FeaturedProperties)
    {
    <div class="col-md-6 col-lg-4">
        <div
             class="portfolio-item mx-auto modal-content"
             data-toggle="modal"
             data-target="#modalContainer"
             data-contenturl="@Url.RouteUrl("PropertyDetailsRoute", new { propertyId = featuredProperty.Property.Id })">
            <div class="portfolio-item-caption d-flex align-items-center justify-content-center h-100 w-100">
                <div class="portfolio-item-caption-content text-center text-white">
                    <i class="fas fa-plus fa-3x"></i>
                </div>
            </div>
            <img class="img-fluid" src="@featuredProperty.ImageUrl" alt="">
            <span class="text-center">@featuredProperty.Property.Name</span>
        </div>
    </div>
    }
</div>

src/Views/ObjectDetails/Details.cshtml
@model RealEstate.Models.RealEstateObjectViewModel

@{
    ViewData["Title"] = "Details";
}

<div class="row">
    <div class="container text-center">
        <div class="row justify-content-center">
            <div class="col-lg-8">
                <!-- Portfolio Modal - Title -->
                <h2 class="portfolio-modal-title text-secondary text-uppercase mb-0">@Model.Object.Name</h2>
                <!-- Icon Divider -->
                <div class="divider-custom">
                    <div class="divider-custom-line"></div>
                    <div class="divider-custom-icon">
                        <i class="fas fa-star"></i>
                    </div>
                    <div class="divider-custom-line"></div>
                </div>
                <!-- Portfolio Modal - Image -->
                <img class="img-fluid rounded mb-5" src="@Model.ImageUrl" alt="">
                <!-- Portfolio Modal - Text -->
                <p>
                    Number of bathrooms: @Model.Object.NumberOfBathrooms<br />
                    Number of bedrooms: @Model.Object.NumberOfBedrooms<br />
                    <b>Price: @Model.Object.Price</b>
                </p>
                <p class="mb-5">
                    @Model.Object.Description
                </p>
            </div>
        </div>
    </div>
</div>

src/Views/ObjectList/List.cshtml
@model RealEstate.Models.ObjectListViewModel

@{
    ViewData["Title"] = "Object list";
}

<!-- Portfolio Section Heading -->
<h2 class="page-section-heading text-center text-uppercase text-secondary mb-0">Our objects</h2>

<!-- Icon Divider -->
<div class="divider-custom">
    <div class="divider-custom-line"></div>
    <div class="divider-custom-icon">
        <i class="fas fa-star"></i>
    </div>
    <div class="divider-custom-line"></div>
</div>

<!-- Portfolio Grid Items -->
<div class="row">
    @foreach (var item in Model.Objects)
    {
        <div class="col-md-6 col-lg-4">
            <div class="portfolio-item mx-auto modal-content"
                 data-toggle="modal"
                 data-target="#modalContainer"
                 data-contenturl="@Url.RouteUrl("ObjectDetailsRoute", new { objectId = item.Object.Id })">
                <div class="portfolio-item-caption d-flex align-items-center justify-content-center h-100 w-100">
                    <div class="portfolio-item-caption-content text-center text-white">
                        <i class="fas fa-plus fa-3x"></i>
                    </div>
                </div>
                <img class="img-thumbnail rounded" src="@item.ImageUrl" alt="">
                <span class="text-center">@item.Object.Name</span>
            </div>
        </div>
    }
</div>
</div>

src/Views/PropertyDetails/Details.cshtml
@model RealEstate.Models.PropertyViewModel

@{
    ViewData["Title"] = "Details";
}

<div class="row">
    <div class="container text-center">
        <div class="row justify-content-center">
            <div class="col-lg-8">
                <!-- Portfolio Modal - Title -->
                <h2 class="portfolio-modal-title text-secondary text-uppercase mb-0">@Model.Property.Name</h2>
                <!-- Icon Divider -->
                <div class="divider-custom">
                    <div class="divider-custom-line"></div>
                    <div class="divider-custom-icon">
                        <i class="fas fa-star"></i>
                    </div>
                    <div class="divider-custom-line"></div>
                </div>
                <!-- Portfolio Modal - Image -->
                <img class="img-fluid rounded mb-5" src="@Model.ImageUrl" alt="">
                <!-- Portfolio Modal - Text -->
                <p>
                    Number of bathrooms: @Model.Property.NumberOfBathrooms<br />
                    Number of bedrooms: @Model.Property.NumberOfBedrooms<br />
                    <b>Price: @Model.Property.Price</b>
                </p>
                <p class="mb-5">
                    @Model.Property.Description
                </p>
            </div>
        </div>
    </div>
</div>

src/Views/PropertyList/List.cshtml
@model RealEstate.Models.PropertyListViewModel

@{
    ViewData["Title"] = "Property list";
}

<!-- Portfolio Section Heading -->
<h2 class="page-section-heading text-center text-uppercase text-secondary mb-0">Our properties</h2>

<!-- Icon Divider -->
<div class="divider-custom">
    <div class="divider-custom-line"></div>
    <div class="divider-custom-icon">
        <i class="fas fa-star"></i>
    </div>
    <div class="divider-custom-line"></div>
</div>

<!-- Portfolio Grid Items -->
<div class="row">
    @foreach (var item in Model.Properties)
    {
        <div class="col-md-6 col-lg-4">
            <div class="portfolio-item mx-auto modal-content"
                 data-toggle="modal"
                 data-target="#modalContainer"
                 data-contenturl="@Url.RouteUrl("PropertyDetailsRoute", new { propertyId = item.Property.Id })">
                <div class="portfolio-item-caption d-flex align-items-center justify-content-center h-100 w-100">
                    <div class="portfolio-item-caption-content text-center text-white">
                        <i class="fas fa-plus fa-3x"></i>
                    </div>
                </div>
                <img class="img-thumbnail rounded" src="@item.ImageUrl" alt="">
                <span class="text-center">@item.Property.Name</span>
            </div>
        </div>
    }
</div>
</div>

src/Views/Shared/_Layout.cshtml
@model RealEstate.Models.BaseViewModel

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>@ViewData["Title"] - RealEstate</title>

    <!-- Custom fonts for this theme -->
    <link href="~/vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Lato:400,700,400italic,700italic" rel="stylesheet" type="text/css">

    <!-- Theme CSS -->
    <environment include="Development">
        <link href="~/css/freelancer.min.css" rel="stylesheet">
    </environment>

    <environment exclude="Development">
        <link href="~/css/freelancer.min.css" rel="stylesheet">
    </environment>
</head>

<body>
    <div class="container">
        <partial name="_CookieConsentPartial" />
    </div>

    <!-- Navigation -->
    <nav class="navbar navbar-expand-lg bg-secondary text-uppercase fixed-top" id="mainNav">
        <div class="container">
            <a class="navbar-brand js-scroll-trigger" href="#page-top">RealEstate</a>
            <button class="navbar-toggler navbar-toggler-right text-uppercase font-weight-bold bg-primary text-white rounded" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                Menu
                <i class="fas fa-bars"></i>
            </button>
            <div class="collapse navbar-collapse" id="navbarResponsive">
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item mx-0 mx-lg-1">
                        <a class="nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                    </li>
                    <li class="nav-item mx-0 mx-lg-1">
                        @Html.ActionLink("Our properties", "GetAllProperties", "PropertyList", null, new { @class = "nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger" } )
                    </li>
                </ul>
            </div>
        </div>
    </nav>

    @if (Model.ShowMasterHeader)
    {
    <header class="masthead bg-primary text-white text-center">
        <div class="container d-flex align-items-center flex-column">
            <!-- Masthead Heading -->
            <h1 class="masthead-heading text-uppercase mb-0">RealEstate Inc.</h1>

            <!-- Icon Divider -->
            <div class="divider-custom divider-light">
                <div class="divider-custom-line"></div>
                <div class="divider-custom-icon">
                    <i class="fas fa-star"></i>
                </div>
                <div class="divider-custom-line"></div>
            </div>

            <!-- Masthead Subheading -->
            <p class="masthead-subheading font-weight-light mb-0">Exclusive - Expensive - Extraterrestrial</p>

        </div>
    </header>
    }

    <section class="page-section portfolio" id="portfolio">
        <div class="container">
            @RenderBody()
        </div>
    </section>

    <!-- Footer -->
    <footer class="footer text-center">
        <div class="container">
            <div class="row">

                <!-- Footer Location -->
                <div class="col-lg-4 mb-5 mb-lg-0">
                    <h4 class="text-uppercase mb-4">Location</h4>
                    <p class="lead mb-0">
                        4711 Sunshine Coast
                        <br>Los Angeles, 50321
                    </p>
                </div>

                <!-- Footer Social Icons -->
                <div class="col-lg-4 mb-5 mb-lg-0">
                    @*<h4 class="text-uppercase mb-4">Around the Web</h4>
                        <a class="btn btn-outline-light btn-social mx-1" href="#">
                            <i class="fab fa-fw fa-facebook-f"></i>
                        </a>
                        <a class="btn btn-outline-light btn-social mx-1" href="#">
                            <i class="fab fa-fw fa-twitter"></i>
                        </a>
                        <a class="btn btn-outline-light btn-social mx-1" href="#">
                            <i class="fab fa-fw fa-linkedin-in"></i>
                        </a>
                        <a class="btn btn-outline-light btn-social mx-1" href="#">
                            <i class="fab fa-fw fa-dribbble"></i>
                        </a>*@
                </div>

                <!-- Footer About Text -->
                <div class="col-lg-4">
                    <h4 class="text-uppercase mb-4">RealEstate Inc.</h4>
                    <p class="lead mb-0">
                        You want to spend the money. We happily take it.
                    </p>
                </div>

            </div>
        </div>
    </footer>

    <!-- Copyright Section -->
    <section class="copyright py-4 text-center text-white">
        <div class="container">
            <small>Copyright &copy; RealEstate Inc. 2019</small>
        </div>
    </section>

    <!-- Scroll to Top Button (Only visible on small and extra-small screen sizes) -->
    <div class="scroll-to-top d-lg-none position-fixed ">
        <a class="js-scroll-trigger d-block text-center text-white rounded" href="#page-top">
            <i class="fa fa-chevron-up"></i>
        </a>
    </div>

    <!-- Modal container -->
    <div class="portfolio-modal modal fade" id="modalContainer" tabindex="-1" role="dialog">
        <div class="modal-dialog modal-xl" role="document">
            <div class="modal-content">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">
                        <i class="fas fa-times"></i>
                    </span>
                </button>
                <div class="modal-body" id="modalBody">
                    Please wait...we're loading...wish we had some cloud power to speed things up!
                </div>
                @*<div class="modal-footer">
                    Footer
                </div>*@
            </div>
        </div>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o">
        </script>
    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/js/freelancer.min.js" asp-append-version="true"></script>
    <script src="~/js/jqBootstrapValidation.min.js" asp-append-version="true"></script>
    <script src="~/js/contact_me.min.js" asp-append-version="true"></script>

    <script type="text/javascript">
        $(document).ready(function () {
            $("body").on("click", ".modal-content", function (e) {
                var contentUrl = $(this).data("contenturl");
                if (contentUrl != null) {
                    e.preventDefault();
                    $("#modalBody").load(contentUrl);
                }
            });
        });
    </script>

    @RenderSection("Scripts", required: false)
</body>
</html>

src/Views/Shared/_ObjectDetailsModal.cshtml
@model RealEstate.Models.RealEstateObjectViewModel

<div class="container text-center">
    <div class="row justify-content-center">
        <div class="col-lg-8">
            <!-- Portfolio Modal - Title -->
            <h2 class="portfolio-modal-title text-secondary text-uppercase mb-0">@Model.Object.Name</h2>
            <!-- Icon Divider -->
            <div class="divider-custom">
                <div class="divider-custom-line"></div>
                <div class="divider-custom-icon">
                    <i class="fas fa-star"></i>
                </div>
                <div class="divider-custom-line"></div>
            </div>
            <!-- Portfolio Modal - Image -->
            <img class="img-fluid rounded mb-5" src="@Model.ImageUrl" alt="">
            <!-- Portfolio Modal - Text -->
            <p>
                <b>Price: @Model.Object.Price</b>
            </p>
            <p class="mb-5">
                @Model.Object.Description
            </p>
            @Html.ActionLink("Show all details", "Details", "ObjectDetails", new { objectId = Model.Object.Id }, new { @class = "btn-link" })
        </div>
    </div>
</div>

src/Views/Shared/_PropertyDetailsModal.cshtml
@model RealEstate.Models.PropertyViewModel

<div class="container text-center">
    <div class="row justify-content-center">
        <div class="col-lg-8">
            <!-- Portfolio Modal - Title -->
            <h2 class="portfolio-modal-title text-secondary text-uppercase mb-0">@Model.Property.Name</h2>
            <!-- Icon Divider -->
            <div class="divider-custom">
                <div class="divider-custom-line"></div>
                <div class="divider-custom-icon">
                    <i class="fas fa-star"></i>
                </div>
                <div class="divider-custom-line"></div>
            </div>
            <!-- Portfolio Modal - Image -->
            <img class="img-fluid rounded mb-5" src="@Model.ImageUrl" alt="">
            <!-- Portfolio Modal - Text -->
            <p>
                <b>Price: @Model.Property.Price</b>
            </p>
            <p class="mb-5">
                @Model.Property.Description
            </p>
            @Html.ActionLink("Show all details", "Details", "PropertyDetails", new { propertyId = Model.Property.Id }, new { @class = "btn-link" })
        </div>
    </div>
</div>